

import urllib.request
import json
import codecs
#Generated Locu API created from https://dev.locu.com/
locu_api = '4fda38a894269e7abed0b1b5c4af272a4c82decd'
#Base URL sample for syntax reference. This doesn't do anything in the code.
url = 'https://api.locu.com/v1_0/venue/search/?name=hello&locality=Conway&cuisine=Asian&api_key=4fda38a894269e7abed0b1b\
5c4af272a4c82decd'

#Dictionary used to store values entered by the user. This will be passed later into the restaurant_search function
object_dict = {}

#Input State, store in object_dict
state = input("Please enter your State:")
object_dict['State'] = state

#Input City, store in object_dict
locality = input("Please enter City Name:")
locality = locality.replace(' ', '%20')
object_dict['City'] = locality

#prompts user on name of restaurant, if yes, input and store in object_dict
print("Would you like to enter the name of the restaurant?")
choice = input('Y/y for yes or N/n for no: ')
if choice == 'Y' or choice == 'y':
    rest_name = input("Please enter name of restaurant: ")
else:
    rest_name = None
object_dict['Restaurant'] = rest_name

#prompts user on type of cuisine, if yes, input and store in object_dict
print("Would you like to enter the cuisine of the restaurant?")
choice = input('Y/y for yes or N/n for no: ')
if choice == 'Y' or choice == 'y':
    food_type = input("Please enter desired cuisine: ")
else:
    food_type = None
object_dict['Cuisine'] = food_type

#function used to grab data from LocuAPI and display it to the user
def restaurant_search(**object_dict):
    #new_url generated based on user input. Attaches City name and State name to the URL
    new_url = 'https://api.locu.com/v1_0/venue/search/?api_key=4fda38a894269e7abed0b1b5c4af272a4c82decd'
    new_url = 'https://api.locu.com/v1_0/venue/search/?api_key=4fda38a894269e7abed0b1b5c4af272a4c82decd' \
        + "&locality=" + object_dict['City'] + '&region=' + object_dict['State']

    #Attaches Restaurant name to the URL if the value in object_dict['Restaurant'] is not none.
    if object_dict['Restaurant'] is not None:
        new_url = 'https://api.locu.com/v1_0/venue/search/?api_key=4fda38a894269e7abed0b1b5c4af272a4c82decd' \
            + "&locality=" + object_dict['City'] + '&name=' + object_dict['Restaurant'] \
            + '&region=' + object_dict['State']

    #Attaches 'Cuisine name to the URL if the value in object_dict['Cuisine'] is not none.
    if object_dict['Cuisine'] is not None:
        new_url = 'https://api.locu.com/v1_0/venue/search/?api_key=4fda38a894269e7abed0b1b5c4af272a4c82decd' \
            + '&locality=' + object_dict['City']+ '&cuisine=' + object_dict['Cuisine'] \
            + '&region=' + object_dict['State']

    #Make request to Locu API based on the generated URL
    request = urllib.request.urlopen(new_url)

    #Convert Request byte code to utf-8 for json.load
    reader = codecs.getreader("utf-8")
    #Store the data generated by json.load into data
    data = json.load(reader(request))

    #Iterate through data, pull out name, phone number, and street address based on search queries
    for each in data['objects']:
        print (each['name'])
        print (each['phone'])
        print (each['street_address'], '\n')
        print ('-------------------')

restaurant_search(**object_dict)



